"""Independent CMS/PKCS#7 signing service backed by cryptography/OpenSSL bindings."""

from __future__ import annotations

import os
import sys
import tempfile
import json
import hashlib
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable

_LOCAL_PACKAGES = Path(__file__).resolve().parent / ".python-packages"
if _LOCAL_PACKAGES.is_dir():
    sys.path.insert(0, str(_LOCAL_PACKAGES))

from cryptography import x509
from cryptography.exceptions import UnsupportedAlgorithm
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, padding, rsa
from cryptography.hazmat.primitives.serialization import pkcs7
from cryptography.x509.oid import NameOID


ProgressCallback = Callable[[int, int], None]
MAX_RECOMMENDED_FILE_SIZE = 512 * 1024 * 1024


class SigningError(Exception):
    """Base exception intended for user-facing signing failures."""


class SigningMaterialError(SigningError):
    pass


class CertificateExpiredError(SigningMaterialError):
    pass


class KeyCertificateMismatchError(SigningMaterialError):
    pass


class InputFileError(SigningError):
    pass


class OutputFileError(SigningError):
    pass


class AlgorithmNotSupportedError(SigningError):
    pass


class VerificationError(SigningError):
    pass


@dataclass(frozen=True)
class CertificateInfo:
    subject: str
    issuer: str
    not_valid_before: datetime
    not_valid_after: datetime
    serial_number: str
    sha256_fingerprint: str

    @property
    def status(self) -> str:
        now = datetime.now(timezone.utc)
        if now < self.not_valid_before:
            return "未生效"
        if now > self.not_valid_after:
            return "已过期"
        return "有效"


@dataclass(frozen=True)
class SigningResult:
    path: Path
    source_sha256: str
    signature_sha256: str
    certificate: CertificateInfo
    verified: bool


class P7SSigningService:
    """Creates detached DER PKCS#7 signatures without invoking an executable."""

    def __init__(self, private_key_path: Path, certificate_path: Path) -> None:
        self.private_key_path = Path(private_key_path)
        self.certificate_path = Path(certificate_path)

    def sign_file(
        self, source: Path, destination: Path, progress: ProgressCallback | None = None, *, overwrite: bool = False
    ) -> SigningResult:
        """Sign *source* and atomically publish its detached .p7s file at *destination*.

        The source is deliberately read in chunks to provide byte-accurate read
        progress.  CMS construction itself currently requires a bytes payload in
        cryptography's public API, so the input must fit in memory.
        """
        source, destination = Path(source), Path(destination)
        self._validate_paths(source, destination, overwrite)
        key, certificate = self._load_signing_material()
        content = self._read_with_progress(source, progress)
        try:
            signed = (
                pkcs7.PKCS7SignatureBuilder()
                .set_data(content)
                .add_signer(certificate, key, hashes.SHA256())
                .sign(
                    serialization.Encoding.DER,
                    [
                        pkcs7.PKCS7Options.DetachedSignature,
                        pkcs7.PKCS7Options.Binary,
                        pkcs7.PKCS7Options.NoAttributes,
                    ],
                )
            )
        except UnsupportedAlgorithm as exc:
            raise AlgorithmNotSupportedError("当前 OpenSSL 后端不支持此证书的签名算法。") from exc
        except ValueError as exc:
            raise SigningError(f"无法生成 PKCS#7 签名：{exc}") from exc
        self._atomic_write(destination, signed)
        try:
            self.verify_detached_signature(source, destination, certificate)
        except SigningError:
            raise
        except Exception as exc:
            raise VerificationError("签名文件已生成，但自动验签未通过。") from exc
        if progress:
            progress(len(content), len(content))
        return SigningResult(
            path=destination,
            source_sha256=hashlib.sha256(content).hexdigest(),
            signature_sha256=hashlib.sha256(signed).hexdigest(),
            certificate=self.get_certificate_info(certificate),
            verified=True,
        )

    def get_signing_certificate_info(self) -> CertificateInfo:
        """Return certificate metadata for UI display."""
        _, certificate = self._load_signing_material()
        return self.get_certificate_info(certificate)

    def verify_detached_signature(self, source: Path, signature_path: Path, certificate: x509.Certificate | None = None) -> None:
        """Verify the detached CMS signature generated by this service.

        cryptography can create PKCS#7/CMS signatures but does not expose a full
        public CMS verifier.  This verifier deliberately supports the exact
        output profile used here: DER, detached, binary, no signed attributes.
        """
        source, signature_path = Path(source), Path(signature_path)
        if certificate is None:
            _, certificate = self._load_signing_material()
        try:
            content = source.read_bytes()
            signature_der = signature_path.read_bytes()
        except OSError as exc:
            raise VerificationError("自动验签失败：无法读取原文件或签名文件。") from exc
        parsed = _extract_cms_noattr_signature(signature_der)
        if parsed["content_type_oid"] != "1.2.840.113549.1.7.2":
            raise VerificationError("自动验签失败：签名文件不是 CMS SignedData。")
        if parsed["digest_oid"] not in {"2.16.840.1.101.3.4.2.1", "1.3.14.3.2.26"}:
            raise VerificationError("自动验签失败：不支持的摘要算法。")
        if parsed["signature_oid"] not in {"1.2.840.10045.4.3.2", "1.2.840.113549.1.1.11"}:
            raise VerificationError("自动验签失败：不支持的签名算法。")

        public_key = certificate.public_key()
        digest = hashes.SHA256() if parsed["digest_oid"] == "2.16.840.1.101.3.4.2.1" else hashes.SHA1()
        try:
            if isinstance(public_key, ec.EllipticCurvePublicKey):
                public_key.verify(parsed["signature"], content, ec.ECDSA(digest))
            elif isinstance(public_key, rsa.RSAPublicKey):
                public_key.verify(parsed["signature"], content, padding.PKCS1v15(), digest)
            else:
                raise VerificationError("自动验签失败：不支持当前证书公钥类型。")
        except VerificationError:
            raise
        except Exception as exc:
            raise VerificationError("自动验签失败：签名内容与原文件或证书不匹配。") from exc

    @staticmethod
    def get_certificate_info(certificate: x509.Certificate) -> CertificateInfo:
        return CertificateInfo(
            subject=_format_name(certificate.subject),
            issuer=_format_name(certificate.issuer),
            not_valid_before=certificate.not_valid_before_utc,
            not_valid_after=certificate.not_valid_after_utc,
            serial_number=f"{certificate.serial_number:X}",
            sha256_fingerprint=certificate.fingerprint(hashes.SHA256()).hex().upper(),
        )

    def _validate_paths(self, source: Path, destination: Path, overwrite: bool) -> None:
        if not source.is_file():
            raise InputFileError("待签名文件不存在，或不是普通文件。")
        if not os.access(source, os.R_OK):
            raise InputFileError("没有读取待签名文件的权限。")
        if not destination.parent.is_dir():
            raise OutputFileError("保存目录不存在。")
        if not os.access(destination.parent, os.W_OK):
            raise OutputFileError("没有写入目标目录的权限。")
        if destination.exists() and not overwrite:
            raise OutputFileError("目标文件已存在；请确认后再执行覆盖。")

    def _load_signing_material(self):
        if not self.private_key_path.is_file() or not self.certificate_path.is_file():
            raise SigningMaterialError("未找到 private_key.pem 或 user.crt。")
        try:
            key = serialization.load_pem_private_key(self.private_key_path.read_bytes(), password=None)
        except TypeError as exc:
            raise SigningMaterialError("私钥受口令保护；当前版本不支持无提示读取此私钥。") from exc
        except (ValueError, OSError) as exc:
            raise SigningMaterialError("私钥文件损坏、格式不正确或无法读取。") from exc
        try:
            certificate = x509.load_pem_x509_certificate(self.certificate_path.read_bytes())
        except (ValueError, OSError) as exc:
            raise SigningMaterialError("证书文件损坏、格式不正确或无法读取。") from exc
        now = datetime.now(timezone.utc)
        if not (certificate.not_valid_before_utc <= now <= certificate.not_valid_after_utc):
            raise CertificateExpiredError("签名证书尚未生效或已过期。")
        key_public = key.public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
        cert_public = certificate.public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
        if key_public != cert_public:
            raise KeyCertificateMismatchError("私钥与签名证书不匹配。")
        return key, certificate

    @staticmethod
    def _read_with_progress(source: Path, progress: ProgressCallback | None) -> bytes:
        total, completed, chunks = source.stat().st_size, 0, []
        try:
            with source.open("rb") as stream:
                while chunk := stream.read(1024 * 1024):
                    chunks.append(chunk)
                    completed += len(chunk)
                    if progress:
                        progress(completed, total)
        except OSError as exc:
            raise InputFileError("读取待签名文件时发生错误。") from exc
        if progress and total == 0:
            progress(0, 0)
        return b"".join(chunks)

    @staticmethod
    def _atomic_write(destination: Path, content: bytes) -> None:
        temporary_path: str | None = None
        try:
            fd, temporary_path = tempfile.mkstemp(prefix=f".{destination.name}.", suffix=".tmp", dir=destination.parent)
            with os.fdopen(fd, "wb") as stream:
                stream.write(content)
                stream.flush()
                os.fsync(stream.fileno())
            os.replace(temporary_path, destination)
            temporary_path = None
        except OSError as exc:
            raise OutputFileError("写入签名文件失败；请检查磁盘空间和文件夹权限。") from exc
        finally:
            if temporary_path:
                try:
                    os.unlink(temporary_path)
                except OSError:
                    pass


class AuditLogger:
    """Append-only local JSONL audit log; never stores private key or file data."""

    def __init__(self, log_path: Path) -> None:
        self.log_path = Path(log_path)

    def record_success(self, source: Path, result: SigningResult) -> None:
        self._write(
            {
                "event": "sign_success",
                "time": datetime.now(timezone.utc).isoformat(),
                "source_name": Path(source).name,
                "source_path": str(Path(source).resolve()),
                "source_sha256": result.source_sha256,
                "signature_path": str(result.path.resolve()),
                "signature_sha256": result.signature_sha256,
                "certificate_subject": result.certificate.subject,
                "certificate_fingerprint_sha256": result.certificate.sha256_fingerprint,
                "verified": result.verified,
            }
        )

    def record_failure(self, source: Path | None, destination: Path | None, error: Exception) -> None:
        self._write(
            {
                "event": "sign_failure",
                "time": datetime.now(timezone.utc).isoformat(),
                "source_name": Path(source).name if source else None,
                "source_path": str(Path(source).resolve()) if source else None,
                "signature_path": str(Path(destination).resolve()) if destination else None,
                "error_type": type(error).__name__,
                "error": str(error),
            }
        )

    def _write(self, payload: dict) -> None:
        try:
            self.log_path.parent.mkdir(parents=True, exist_ok=True)
            with self.log_path.open("a", encoding="utf-8") as stream:
                stream.write(json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n")
        except OSError:
            # Audit logging must not block signing workflow.
            pass


def _format_name(name: x509.Name) -> str:
    common_names = name.get_attributes_for_oid(NameOID.COMMON_NAME)
    if common_names:
        return common_names[0].value
    return ", ".join(f"{attr.oid._name}={attr.value}" for attr in name)


class _DerNode:
    def __init__(self, tag: int, value: bytes) -> None:
        self.tag = tag
        self.value = value

    def children(self) -> list["_DerNode"]:
        nodes, offset = [], 0
        while offset < len(self.value):
            node, offset = _read_der_node(self.value, offset)
            nodes.append(node)
        return nodes


def _read_der_node(data: bytes, offset: int = 0) -> tuple[_DerNode, int]:
    if offset >= len(data):
        raise VerificationError("自动验签失败：签名文件结构不完整。")
    tag = data[offset]
    offset += 1
    if offset >= len(data):
        raise VerificationError("自动验签失败：签名文件长度不完整。")
    first_length = data[offset]
    offset += 1
    if first_length & 0x80:
        length_octets = first_length & 0x7F
        if length_octets == 0 or length_octets > 4 or offset + length_octets > len(data):
            raise VerificationError("自动验签失败：签名文件长度非法。")
        length = int.from_bytes(data[offset : offset + length_octets], "big")
        offset += length_octets
    else:
        length = first_length
    end = offset + length
    if end > len(data):
        raise VerificationError("自动验签失败：签名文件内容截断。")
    return _DerNode(tag, data[offset:end]), end


def _decode_oid(value: bytes) -> str:
    if not value:
        raise VerificationError("自动验签失败：OID 为空。")
    first = value[0]
    parts = [first // 40, first % 40]
    number = 0
    for byte in value[1:]:
        number = (number << 7) | (byte & 0x7F)
        if not byte & 0x80:
            parts.append(number)
            number = 0
    if number:
        raise VerificationError("自动验签失败：OID 编码非法。")
    return ".".join(str(part) for part in parts)


def _expect_child_oid(node: _DerNode, index: int = 0) -> str:
    children = node.children()
    if len(children) <= index or children[index].tag != 0x06:
        raise VerificationError("自动验签失败：签名算法结构异常。")
    return _decode_oid(children[index].value)


def _extract_cms_noattr_signature(signature_der: bytes) -> dict:
    root, end = _read_der_node(signature_der)
    if end != len(signature_der) or root.tag != 0x30:
        raise VerificationError("自动验签失败：签名文件不是合法 DER SEQUENCE。")
    content_info = root.children()
    if len(content_info) != 2 or content_info[0].tag != 0x06 or content_info[1].tag != 0xA0:
        raise VerificationError("自动验签失败：CMS ContentInfo 结构异常。")
    signed_data_wrapper = content_info[1].children()
    if len(signed_data_wrapper) != 1 or signed_data_wrapper[0].tag != 0x30:
        raise VerificationError("自动验签失败：CMS SignedData 结构异常。")
    signed_data = signed_data_wrapper[0].children()
    if len(signed_data) < 5:
        raise VerificationError("自动验签失败：SignedData 字段不足。")

    digest_algorithms = signed_data[1].children()
    if not digest_algorithms:
        raise VerificationError("自动验签失败：缺少摘要算法。")
    digest_oid = _expect_child_oid(digest_algorithms[0])

    signer_infos = signed_data[-1]
    if signer_infos.tag != 0x31:
        raise VerificationError("自动验签失败：缺少 SignerInfo。")
    signer_info_items = signer_infos.children()
    if len(signer_info_items) != 1 or signer_info_items[0].tag != 0x30:
        raise VerificationError("自动验签失败：当前仅支持单证书签名。")
    signer_info = signer_info_items[0].children()
    if len(signer_info) < 5:
        raise VerificationError("自动验签失败：SignerInfo 字段不足。")

    # NoAttributes output profile: version, sid, digestAlgorithm,
    # signatureAlgorithm, signature OCTET STRING.
    if signer_info[3].tag != 0x30 or signer_info[4].tag != 0x04:
        raise VerificationError("自动验签失败：当前仅支持无签名属性的 detached P7S。")
    return {
        "content_type_oid": _decode_oid(content_info[0].value),
        "digest_oid": digest_oid,
        "signature_oid": _expect_child_oid(signer_info[3]),
        "signature": signer_info[4].value,
    }
